package pack1;

public class exceptionExample {
	
	public static void main(String[] args)  throws ArithmeticException
	{
	  System.out.println("first line of the code");
	 
	  
	  System.out.println("Inside try block1");	  
	  int a=10/0; // control will go immediately catch block
	  System.out.println("Inside try block2");	
	  
	 
	  
	}

}
